name: Elixir Phoenix package CI

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
  schedule:
    - cron: "0 0 * * 1-5"
  workflow_dispatch:

jobs:
  validate-changesets:
    uses: ./.github/workflows/validate_changesets.yml

  lint_git:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'schedule' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: lintje/action@v0.11

  lint_format:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 28.x
          elixir-version: 1.19.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check code formatting
        run: mix format --check-formatted

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: 28.x
          elixir-version: 1.19.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get
      - name: Build the package
        run: mix hex.build
